### ISSUE TITLE
Criação do documento de metologia

### ISSUE THREAD

**Issue by RcleydsonR** [Requisitos-de-Software/2021.1-Ingresso.com#4]
# Descrição
Criar o documento de metodologia do projeto, que ira conter as metodologias que serão utilizadas durante o processo de desenvolvimento do trabalho, bem como a política de branchs que irá ser seguida

# Tarefas

- [x]  Conter o documento de metodologia
- [x] Conter a política de branchs
- [x] Criação do heatmap (Disponibilidade dos membros na semana)

**Comment by CarlosFiuza** [comment]
Metodologia e política de branches adicionadas a documentação.
