### ISSUE TITLE
Modelagem NFR Framework

### ISSUE THREAD

**Issue by RcleydsonR** [Requisitos-de-Software/2021.1-Ingresso.com#67]
### Descrição:

Será documentada a abordagem que modela requisitos Não funcionais conhecida como NFR Framework

### Tarefas:

- [x]  Introdução ao NFR Framework
- [x] Adição do documento com introdução e imagens

### Critérios de aceitação:

- [x] Documento estar disponível na wiki

**Comment by thiagohdaqw** [comment]
os diagramas estao sendo feitos nesse lugar: https://drive.google.com/file/d/1CqGDRZzs1NwnH79M2zhNEMZbQFCS0aDX/view?usp=sharing
